# SPDX-License-Identifier: MIT

[package]
name = "mwl"
version = "0.0.0"
description = "The minewell command-line interface"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
miette = { version = "7", features = ["fancy"] }
mwlc = { path = "../mwlc" }

[lints]
workspace = true
